import type { Settings } from './types'

// Defaults mirror grainrad's initial settings (see extracted spec).
export const DEFAULT_SETTINGS: Settings = {
  active: 'ascii',
  ascii: {
    scale: 2,
    spacing: 0,
    outputWidth: 0,
    set: 'standard',
    customChars: ' .:+*#@',
    brightness: 0,
    contrast: 0,
    saturation: 0,
    hue: 0,
    sharpness: 0,
    gamma: 1,
    colorMode: 'original',
    custom: '#00ff00',
    backgroundColor: '#000000',
    intensity: 1,
    invert: false,
    brightnessMapping: 1,
    edgeEnhance: 0,
    blur: 0,
    quantizeColors: 0,
  },
  waveLines: {
    lineCount: 50,
    amplitude: 20,
    frequency: 1,
    direction: 'horizontal',
    lineThickness: 1,
    colorMode: 'original',
    fgColor: '#ffffff',
    bgColor: '#000000',
    brightness: 0,
    contrast: 0,
  },
  dithering: {
    method: 'bayer8x8',
    intensity: 1,
    colorMode: 'mono',
    colorLevels: 2,
    gamma: 1,
    sharpen: 0,
    foregroundColor: '#FFFFFF',
    backgroundColor: '#000000',
    palette: 'gameboy',
    paletteSize: 2,
    brightness: 0,
    contrast: 0,
  },
  halftone: {
    shape: 'circle',
    dotScale: 1,
    spacing: 8,
    angle: 45,
    invert: false,
    colorMode: 'bw',
    fgColor: '#ffffff',
    bgColor: '#000000',
    brightness: 0,
    contrast: 0,
  },
  pixelSort: {
    direction: 'horizontal',
    mode: 'brightness',
    threshold: 0.25,
    streakLength: 100,
    intensity: 0.8,
    reverse: false,
    brightness: 0,
    contrast: 0,
  },
  dots: {
    shape: 'circle',
    gridType: 'square',
    sizeMultiplier: 1,
    spacing: 1,
    invert: false,
    colorMode: 'original',
    fgColor: '#ffffff',
    bgColor: '#000000',
    brightness: 0,
    contrast: 0,
  },
  contour: {
    fillMode: 'filled',
    levels: 8,
    lineThickness: 1,
    invert: false,
    colorMode: 'original',
    lineColor: '#000000',
    bgColor: '#ffffff',
    brightness: 0,
    contrast: 0,
  },
  edgeDetection: {
    algorithm: 'sobel',
    threshold: 0.3,
    lineWidth: 1,
    invert: false,
    colorMode: 'custom',
    edgeColor: '#ffffff',
    bgColor: '#000000',
    brightness: 0,
    contrast: 0,
  },
  crosshatch: {
    density: 6,
    layers: 3,
    angle: 45,
    lineWidth: 1,
    randomness: 0,
    invert: false,
    fgColor: '#000000',
    bgColor: '#ffffff',
    brightness: 0,
    contrast: 0,
  },
  blockify: {
    style: 'full',
    blockSize: 8,
    borderWidth: 1,
    colorMode: 'color',
    borderColor: '#000000',
    brightness: 0,
    contrast: 0,
  },
  threshold: {
    levels: 2,
    thresholdPoint: 0.5,
    dither: false,
    invert: false,
    colorMode: 'custom',
    fgColor: '#ffffff',
    bgColor: '#000000',
    brightness: 0,
    contrast: 0,
  },
  noiseField: {
    noiseType: 'perlin',
    scale: 50,
    intensity: 1,
    octaves: 4,
    speed: 1,
    animate: true,
    distortOnly: false,
    brightness: 0,
    contrast: 0,
  },
  matrixRain: {
    characterSet: 'standard',
    customChars:
      'ｱｲｳｴｵｶｷｸｹｺｻｼｽｾｿﾀﾁﾂﾃﾄﾅﾆﾇﾈﾉﾊﾋﾌﾍﾎﾏﾐﾑﾒﾓﾔﾕﾖﾗﾘﾙﾚﾛﾜﾝ0123456789',
    cellSize: 12,
    spacing: 0,
    speed: 1,
    trailLength: 15,
    direction: 'down',
    glowIntensity: 1,
    bgOpacity: 0.3,
    rainColor: '#00ff00',
    brightness: 0,
    contrast: 0,
    threshold: 0,
  },
  vhs: {
    distortion: 0.5,
    noise: 0.3,
    colorBleed: 0.5,
    scanlines: 0.3,
    trackingError: 0.2,
    brightness: 0,
    contrast: 0,
  },
  voronoi: {
    cellSize: 30,
    edgeWidth: 0.3,
    edgeColor: 0,
    colorMode: 0,
    randomize: 0.8,
    brightness: 0,
    contrast: 0,
  },
  post: {
    bloom: { enabled: false, threshold: 0.3, softThreshold: 0.2, intensity: 1.5, radius: 12 },
    grain: { enabled: false, intensity: 35, size: 2, speed: 50 },
    chromatic: { enabled: false, offset: 2 },
    scanlines: { enabled: false, opacity: 0.1, spacing: 4 },
    vignette: { enabled: false, intensity: 0.5, radius: 0.5 },
    crtCurve: { enabled: false, amount: 0.1 },
    phosphor: { enabled: false, color: 'green', customColor: '#00ff00' },
  },
  output: {
    background: '#000000',
    showOriginal: false,
    maxPreviewDim: 4096,
  },
}
